## Zookeeper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-worker-0
  template:
    metadata:
      labels:
        app: edge-worker-0
    spec:
      containers:
      - name: edge-worker-0
        image: mfatihaktas/edge-load-balance
        ports:
        - containerPort: 5000
        command: ["python3", "-u"]
        args: ["/home/app/worker.py", "--log_to_std=0"]

zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    container_name: zookeeper
    networks:
      - img-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
---

apiVersion: v1
kind: Service
metadata:
  name: edge-worker-service-0
  labels:
    app: edge-worker-service-0
spec:
  clusterIP: None
  selector:
    app: edge-worker-0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-master-0
  labels:
    app: edge-master-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-master-0
  template:
    metadata:
      labels:
        app: edge-master-0
    spec:
      containers:
      - name: edge-master-0
        image: mfatihaktas/edge-load-balance
        ports:
        - containerPort: 5000
        command: ["python3", "-u"]
        args: ["/home/app/master.py", "--log_to_std=0", "--worker_service=edge-worker-service-0"]

---

apiVersion: v1
kind: Service
metadata:
  name: edge-master-service-0
spec:
  type: LoadBalancer
  selector:
    app: edge-master-0
  ports:
  - name: tcp
    port: 5000
    targetPort: 5000
    nodePort: 30000
    protocol: TCP

---

## Cluster-1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-worker-1
  labels:
    app: edge-worker-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-worker-1
  template:
    metadata:
      labels:
        app: edge-worker-1
    spec:
      containers:
      - name: edge-worker-1
        image: mfatihaktas/edge-load-balance
        ports:
        - containerPort: 5000
        command: ["python3", "-u"]
        args: ["/home/app/worker.py", "--log_to_std=0"]

---

apiVersion: v1
kind: Service
metadata:
  name: edge-worker-service-1
  labels:
    app: edge-worker-service-1
spec:
  clusterIP: None
  selector:
    app: edge-worker-1

---
