# syntax=docker/dockerfile:1
FROM bitnami/kafka:latest
WORKDIR /home/app

# RUN apt-get update
# RUN apt-get install less

# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD [ "python3", "-u", "server.py", "--i=0" ]